# ------------------------------------------------------------------------------
# Prepare npm repo
# ------------------------------------------------------------------------------

before_script:
  - cp "$NPMRC" $HOME/.npmrc

image: node:18
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm
    - node_modules/

stages:
  - check
  - publish

init:
  stage: .pre
  script:
    - npm ci --cache .npm --prefer-offline

check:
  stage: check
  script:
    - node index.js

publish:
  stage: publish
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^release\//'
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - npm publish
