name: ci

permissions:
  contents: read
  id-token: write

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Set up Node.js lts/iron
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: node index.js

  lint:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use node modules cache
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-prepare-${{ env.cache-name }}-${{ github.sha }}

      - name: Run ESLint
        run: npm run lint
